@startuml
Alice -> Bob: Запрос данных
alt авторизация успешна
    Bob --> Alice: Данные получены
else ошибка авторизации
    break токен недействителен
        Bob --> Alice: Ошибка 401 (Выход из процесса)
    end
end
@enduml